name: CI

on:
  - push

jobs:
  test:
    name: lint
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Configure Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.x
      - run: npm install
      - run: npm run lint
      - run: npm run lint:prettier
      - run: npm run lint:react
      - run: npm run lint:typescript
